-- EX02 - Ejecutar directamente en WSn_DEV (solo si EX_CUSTOMERS no existe en DEV)
CREATE TABLE EX_CUSTOMERS (
    CUSTOMER_ID NUMBER(10) PRIMARY KEY,
    FIRST_NAME  VARCHAR2(50),
    LAST_NAME   VARCHAR2(50),
    EMAIL       VARCHAR2(100),
    CREATED_AT  DATE DEFAULT SYSDATE
);
