-- EX01 - Upgrade: crea la tabla EX_CUSTOMERS
CREATE TABLE EX_CUSTOMERS (
    CUSTOMER_ID   NUMBER(10)     NOT NULL,
    FIRST_NAME    VARCHAR2(50)   NOT NULL,
    LAST_NAME     VARCHAR2(50)   NOT NULL,
    EMAIL         VARCHAR2(100),
    CREATED_AT    DATE DEFAULT SYSDATE,
    CONSTRAINT PK_EX_CUSTOMERS PRIMARY KEY (CUSTOMER_ID)
);
